services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - ./data/namenode:/hadoop/dfs/name
      - ./config:/hadoop-config
      - ./scripts:/scripts
      - ./data/csv:/data/csv
      - ./data:/data
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    ports:
      - "9864:9864"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - SERVICE_PRECONDITION=namenode:9870
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    networks:
      - hadoop
    depends_on:
      - namenode

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    ports:
      - "8088:8088" # UI do ResourceManager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - YARN_RESOURCEMANAGER_HOSTNAME=resourcemanager
      - YARN_CONF_yarn_log___aggregation___enable=true
    networks:
      - hadoop
    depends_on:
      - namenode

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - YARN_RESOURCEMANAGER_HOSTNAME=resourcemanager
    networks:
      - hadoop
    depends_on:
      - resourcemanager

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    ports:
      - "8188:8188"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - YARN_RESOURCEMANAGER_HOSTNAME=resourcemanager
      - SERVICE_PRECONDITION=namenode:9870,resourcemanager:8088
    networks:
      - hadoop
    depends_on:
      - namenode
      - datanode
      - resourcemanager
      - nodemanager
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5

  init-hdfs:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    depends_on:
      - namenode
    entrypoint: ["/bin/bash", "-c", "/scripts/load_hdfs.sh"]
    volumes:
      - ./scripts:/scripts
      - ./data/csv:/data/csv
      - ./config:/hadoop-config
    networks:
      - hadoop

networks:
  hadoop:
    driver: bridge
